using Microsoft.EntityFrameworkCore;
using MyApp.Backend.Controllers;
using MyApp.Backend.Models;

namespace MyApp.Backend.Context
{
    public static class ModelBuilderExtension
    {
        public static void Seed(this ModelBuilder modelBuilder)
        {
            // Ide kerülnek a tesztadatok
            DateTime baseCreated = new DateTime(2025, 1, 1);

            var products = new List<Product>
            {
                new Product { ProductId=1,  Name="Fehér kenyér 1 kg",           Description="Friss pékáru",                     Price=499.00m,  QuantityInStock=120, WeightKg=1.0,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=baseCreated.AddDays(3),  Barcode="5991234567890", ProductCode="PA-001", Category="Pékáru",       Rating=4.3m, ImageUrl=null },
                new Product { ProductId=2,  Name="Teljes kiőrlésű zsömle",      Description="Magvas",                            Price=129.00m,  QuantityInStock=300, WeightKg=0.08, IsActive=true,  CreatedDate=baseCreated, ExpirationDate=baseCreated.AddDays(2),  Barcode="5991234567891", ProductCode="PA-002", Category="Pékáru",       Rating=4.6m, ImageUrl=null },
                new Product { ProductId=3,  Name="Tej 1,5% 1 l",                Description="Félzsíros tej, ESL",               Price=359.00m,  QuantityInStock=200, WeightKg=1.02, IsActive=true,  CreatedDate=baseCreated, ExpirationDate=baseCreated.AddDays(10), Barcode="5991234567892", ProductCode="TEJ-015", Category="Tejtermék",   Rating=4.5m, ImageUrl=null },
                new Product { ProductId=4,  Name="Trappista sajt 250 g",        Description="Szeletelt",                         Price=1099.00m, QuantityInStock=90,  WeightKg=0.25, IsActive=true,  CreatedDate=baseCreated, ExpirationDate=baseCreated.AddDays(20), Barcode="5991234567893", ProductCode="SAJT-TR-250", Category="Tejtermék", Rating=4.2m, ImageUrl=null },
                new Product { ProductId=5,  Name="Vaj 200 g",                   Description="82% zsírtartalom",                  Price=1199.00m, QuantityInStock=60,  WeightKg=0.2,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=baseCreated.AddDays(30), Barcode="5991234567894", ProductCode="VAJ-200", Category="Tejtermék",    Rating=4.7m, ImageUrl=null },
                new Product { ProductId=6,  Name="Tojás M 10 db",               Description="Friss, magyar",                     Price=899.00m,  QuantityInStock=150, WeightKg=0.6,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=baseCreated.AddDays(14), Barcode="5991234567895", ProductCode="TOJ-M-10", Category="Alapélelmiszer", Rating=4.8m, ImageUrl=null },
                new Product { ProductId=7,  Name="Kristálycukor 1 kg",          Description="Cukorrépa alapú",                  Price=479.00m,  QuantityInStock=250, WeightKg=1.0,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567896", ProductCode="CUK-1KG", Category="Alapélelmiszer", Rating=4.4m, ImageUrl=null },
                new Product { ProductId=8,  Name="Finomliszt BL55 1 kg",        Description="Sütéshez-főzéshez",                 Price=349.00m,  QuantityInStock=220, WeightKg=1.0,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567897", ProductCode="LISZT-BL55", Category="Alapélelmiszer", Rating=4.5m, ImageUrl=null },
                new Product { ProductId=9,  Name="Napraforgó étolaj 1 l",       Description="Hidegen sajtolt keverék nélkül",    Price=1099.00m, QuantityInStock=140, WeightKg=0.92, IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567898", ProductCode="OLAJ-1L", Category="Alapélelmiszer",  Rating=4.6m, ImageUrl=null },
                new Product { ProductId=10, Name="Pick szalámi 70 g",           Description="Csemege szeletelt",                 Price=899.00m,  QuantityInStock=80,  WeightKg=0.07, IsActive=true,  CreatedDate=baseCreated, ExpirationDate=baseCreated.AddDays(25), Barcode="5991234567899", ProductCode="SZAL-70", Category="Húsáru",        Rating=4.7m, ImageUrl=null },

                new Product { ProductId=11, Name="Csirkemell filé 1 kg",        Description="Hűtött",                           Price=1699.00m, QuantityInStock=70,  WeightKg=1.0,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=baseCreated.AddDays(5),  Barcode="5991234567800", ProductCode="CSIRKEMELL-1", Category="Húsáru",   Rating=4.3m, ImageUrl=null },
                new Product { ProductId=12, Name="Sertéskaraj 1 kg",            Description="Csontos",                          Price=2199.00m, QuantityInStock=50,  WeightKg=1.0,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=baseCreated.AddDays(4),  Barcode="5991234567801", ProductCode="KARAJ-1", Category="Húsáru",        Rating=4.1m, ImageUrl=null },
                new Product { ProductId=13, Name="Alma Idared 1 kg",            Description="Hazai",                            Price=599.00m,  QuantityInStock=160, WeightKg=1.0,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567802", ProductCode="ALMA-ID", Category="Zöldség-gyümölcs", Rating=4.5m, ImageUrl=null },
                new Product { ProductId=14, Name="Banán 1 kg",                  Description="Érett",                            Price=799.00m,  QuantityInStock=180, WeightKg=1.0,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567803", ProductCode="BAN-1", Category="Zöldség-gyümölcs",  Rating=4.6m, ImageUrl=null },
                new Product { ProductId=15, Name="Kaliforniai paprika piros",   Description="Darab",                            Price=399.00m,  QuantityInStock=130, WeightKg=0.2,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567804", ProductCode="PAP-PIROS", Category="Zöldség-gyümölcs", Rating=4.4m, ImageUrl=null },
                new Product { ProductId=16, Name="Paradicsom fürtös 500 g",     Description="Hazai üvegházi",                  Price=699.00m,  QuantityInStock=110, WeightKg=0.5,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567805", ProductCode="PAR-500", Category="Zöldség-gyümölcs", Rating=4.2m, ImageUrl=null },
                new Product { ProductId=17, Name="Uborka kígyó",                Description="Darab",                            Price=299.00m,  QuantityInStock=140, WeightKg=0.35, IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567806", ProductCode="UBI-DB", Category="Zöldség-gyümölcs",   Rating=4.3m, ImageUrl=null },
                new Product { ProductId=18, Name="Rizs A minőség 1 kg",         Description="Hosszúszemű",                      Price=799.00m,  QuantityInStock=190, WeightKg=1.0,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567807", ProductCode="RIZS-A-1", Category="Alapélelmiszer",   Rating=4.6m, ImageUrl=null },
                new Product { ProductId=19, Name="Tészta spagetti 500 g",       Description="Durum",                            Price=459.00m,  QuantityInStock=170, WeightKg=0.5,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567808", ProductCode="TESZ-SP-500", Category="Alapélelmiszer", Rating=4.5m, ImageUrl=null },
                new Product { ProductId=20, Name="Kávé őrölt 250 g",            Description="Arabica blend",                    Price=1599.00m, QuantityInStock=90,  WeightKg=0.25, IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567809", ProductCode="KAVE-OR-250", Category="Ital",        Rating=4.7m, ImageUrl=null },

                new Product { ProductId=21, Name="Ásványvíz szénsavas 1,5 l",   Description="Közepes ásványianyag-tartalom",    Price=199.00m,  QuantityInStock=400, WeightKg=1.5,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567810", ProductCode="VIZ-SZ-1_5", Category="Ital",        Rating=4.3m, ImageUrl=null },
                new Product { ProductId=22, Name="Narancslé 1 l 100%",          Description="Rostos",                           Price=899.00m,  QuantityInStock=120, WeightKg=1.04, IsActive=true,  CreatedDate=baseCreated, ExpirationDate=baseCreated.AddMonths(6), Barcode="5991234567811", ProductCode="NAR-LE-1", Category="Ital",        Rating=4.4m, ImageUrl=null },
                new Product { ProductId=23, Name="Étcsokoládé 70% 100 g",       Description="Prémium kakaótartalom",            Price=699.00m,  QuantityInStock=150, WeightKg=0.1,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=baseCreated.AddMonths(12), Barcode="5991234567812", ProductCode="CSOK-ET-100", Category="Édesség",  Rating=4.8m, ImageUrl=null },
                new Product { ProductId=24, Name="Keksz vajas 200 g",           Description="Teával kiváló",                    Price=499.00m,  QuantityInStock=130, WeightKg=0.2,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=baseCreated.AddMonths(10), Barcode="5991234567813", ProductCode="KEKSZ-VAJ-200", Category="Édesség", Rating=4.2m, ImageUrl=null },
                new Product { ProductId=25, Name="Fogkefe közepes",             Description="Ergonomikus nyél",                 Price=799.00m,  QuantityInStock=100, WeightKg=0.05, IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567814", ProductCode="FOG-KOZ", Category="Háztartás",       Rating=4.1m, ImageUrl=null },
                new Product { ProductId=26, Name="Folyékony szappan 500 ml",    Description="Bőrbarát",                         Price=999.00m,  QuantityInStock=90,  WeightKg=0.55, IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567815", ProductCode="SZAPP-500", Category="Háztartás",     Rating=4.3m, ImageUrl=null },
                new Product { ProductId=27, Name="Mosópor 3 kg",                Description="Univerzális",                      Price=3499.00m, QuantityInStock=60,  WeightKg=3.0,  IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567816", ProductCode="MOSO-3KG", Category="Háztartás",      Rating=4.4m, ImageUrl=null },
                new Product { ProductId=28, Name="Papírzsebkendő 90 db",        Description="Puha, 3 rétegű",                   Price=399.00m,  QuantityInStock=220, WeightKg=0.18, IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567817", ProductCode="ZSEBK-90", Category="Háztartás",       Rating=4.2m, ImageUrl=null },
                new Product { ProductId=29, Name="USB-C kábel 1 m",             Description="Gyors töltés, adatátvitel",        Price=1999.00m, QuantityInStock=75,  WeightKg=0.03, IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567818", ProductCode="USB-C-1M", Category="Elektronika",     Rating=4.6m, ImageUrl=null },
                new Product { ProductId=30, Name="Bluetooth fülhallgató",       Description="Zajszűrés, tok",                   Price=12999.00m,QuantityInStock=40,  WeightKg=0.12, IsActive=true,  CreatedDate=baseCreated, ExpirationDate=null,                   Barcode="5991234567819", ProductCode="BT-EARBUD", Category="Elektronika",    Rating=4.5m, ImageUrl=null }
            };

            modelBuilder.Entity<Product>().HasData(products);
        }
    }
}
